### ISSUE TITLE
From here to Influx

### ISSUE THREAD

**Issue by bsjoelund** [johnwalicki/node-red-contrib-twc-weather#1]
Hello John,

So far I have nothing to report as issue, a bit standstilll on how to get all data into Influx, maybe you can give me some hints.

![WH1080](https://user-images.githubusercontent.com/65829397/88402588-a0ea8280-cdcb-11ea-959c-e971570c2d3d.JPG)

As you can see I have dropped some nodes as there is no function here in Sweden.
I really appreciate you work, it is somewhat easy for an old fart (70) trying to learn something new.

Cheers from Sparreholm Sweden
Bengt Sjölund

**Comment by johnwalicki** [comment]
Hi Bengt - Happy to hear that you are experimenting with Node-RED and my
examples.  I was able to use my PWS key to query your stationID: "ISDERMAN6"
near Sparreholm.  Looks like the weather is nice there.

I have not tried to write the data to InfluxDB.  I did find a InfluxDB node
for Node-RED
https://flows.nodered.org/node/node-red-contrib-influxdb

Happy to help if you have questions
-- John
