### ISSUE TITLE
numericPrecision parameter for 7 day hourly PWS history

### ISSUE THREAD

**Issue by weatherbadger** [johnwalicki/node-red-contrib-twc-weather#11]
Love the TWC API connectors, thanks!
I note you added the numericPrecision parameter setting in the https://github.com/johnwalicki/node-red-contrib-twc-weather/blob/main/pws-current.js connector.

Could do the same and add numericPrecision to the 
https://github.com/johnwalicki/node-red-contrib-twc-weather/blob/main/pws-historical.js
https://github.com/johnwalicki/node-red-contrib-twc-weather/blob/main/pws-recent.js

connectors please?
In Europe we work mainly in Centigrade and charts with decimal temperature accuracy look soooo much nicer!

**Comment by johnwalicki** [comment]
@weatherbadger  Thanks for the suggestion.

I have added numericPrecision to the historical and recent nodes.
I've published node-red-contrib-twc-weather 0.7.0 to npm
```
npm install node-red-contrib-twc-weather
```
Or https://flows.nodered.org/node/node-red-contrib-twc-weather
