### ISSUE TITLE
Iluminance

### ISSUE THREAD

**Issue by jjvelar** [johnwalicki/node-red-contrib-twc-weather#12]
Hi, thanks for your work. Very useful. 
more than an issue, a request: any idea why illuminance (lux) is not available in the API?
My PWS has a sensor for it but Wunderground does not collect the data. 
Any idea on how to get it?
Thanks in advance for your help. 
Best

Jose

**Comment by johnwalicki** [comment]
Hi @jjvelar Thanks for your interest in my node-red weather node. Good question.  My weather station also reports Solar Radiation / lumens. Not certain that TWC API does anything with it. I'll read up on the docs and let you know.

**Comment by johnwalicki** [comment]
TWC API docs are here:
https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit

**Comment by johnwalicki** [comment]
The Weather Underground PWS page displays Solar Radiation.  Here's the nearby firehouse weather station.
https://www.wunderground.com/dashboard/pws/KNJRIDGE9
So there must be an API to retrieve that data.

**Comment by johnwalicki** [comment]
The Current Conditions API returns Solar Radiation
https://docs.google.com/document/d/1KGb8bTVYRsNgljnNH67AMhckY8AQT2FVwZ9urj8SWBs/edit

**Comment by jjvelar** [comment]
Hi John
Thanks for replying.
There is for radiance in W/m2 (solar radiation), but I also would like to
get illuminance in lux.
Can’t find illuminance in the API documentation, but the data is there as
the mobile app WSView Plus shows solar Radiation in W/m2 or lux.
Any idea where to get lux data?
Thanks again

**Comment by johnwalicki** [comment]
The PWS Observations node in this node-red-contrib-twc-weather package will return 
```
payload.observations[0].solarRadiation
```

Here's a guide on W/m2 to Lumens conversion 
https://www.extrica.com/article/21667

**Comment by jjvelar** [comment]
> The PWS Observations node in this node-red-contrib-twc-weather package will return
> 
> ```
> payload.observations[0].solarRadiation
> ```
> 
> Here's a guide on W/m2 to Lumens conversion https://www.extrica.com/article/21667

That worked for me.
Thank you very much, John.
