### ISSUE TITLE
only one question

### ISSUE THREAD

**Issue by ggtux** [johnwalicki/node-red-contrib-twc-weather#2]
Hi John,

great idea for such a program. Only thing I can not find in the examples isthe point to change the gauge from Fahrenheit to Celsius (metric). I have checked everything. Maybe you can give me please a hint.

best regards Gunter

**Comment by johnwalicki** [comment]
Hi Gunter - Glad you enjoyed the PWS dashboard example.  If you want to change the gauge to Metric, you need to modify two nodes:
- In the "Query Historical Data from PWS" section, double click on the PWS Historical node and select "metric" for the Unit of measure.
- In the Change node "Historical Data AvgTemp" that is wired to the output of the PWS Historical node, modify the msg.payload to
```msg.payload.observations[0].metric.tempAvg```

**Comment by ggtux** [comment]
Hi and Thanks, it worked.
