### ISSUE TITLE
Raw data from the PWS

### ISSUE THREAD

**Issue by ggtux** [johnwalicki/node-red-contrib-twc-weather#3]
Hi John,

your example worked for me very well. 
I hope you can tell me how to get to the raw data of me weather station. I just need the rain and wind data but do not have a direct access to the station. One work around is you Node-red scheme. But there has to be a file or what so ever where the actual data are stored, or not?

Thank you in advance

Gunter

**Comment by johnwalicki** [comment]
The PWS API reference is here:
https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY

You can call the API directly and get the data in json format
Just replace <stationid> and <apikey> with your details.  Also remove the <>
https://api.weather.com/v2/pws/observations/current?stationId=<stationid>&format=json&units=m&apiKey=<apikey>

**Comment by ggtux** [comment]
Am Dienstag, den 24.11.2020, 20:42 -0800 schrieb John Walicki:
> The PWS API reference is here:
>
> https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY
>
> You can call the API directly and get the data in json format
>
> Just replace  and  with your details.  Also remove the <>
>
> https://api.weather.com/v2/pws/observations/current?stationId=&format=json&units=m&apiKey=
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Hi John,
thank you very much. That was the aswer I was looking for.
Have a great one and stay healthy.
Gunter
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/johnwalicki/node-red-contrib-twc-weather/issues/3#issuecomment-733459877
> ",
> "url": "
> https://github.com/johnwalicki/node-red-contrib-twc-weather/issues/3#issuecomment-733459877
> ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
