### ISSUE TITLE
Weather alert node?

### ISSUE THREAD

**Issue by jpoeppelman1** [johnwalicki/node-red-contrib-twc-weather#4]
Hello.  I was wondering if you could add a node to query the active weather alerts?

**Comment by johnwalicki** [comment]
While I don't have a severe weather node, I did create a example Node-RED flow that shows severe weather alerts on a map.

https://github.com/johnwalicki/Node-RED-Severe-Weather-Alert-Map

**Comment by johnwalicki** [comment]
That Node-RED flow calls the TWC alerts API (if necessary, several times) to retrieve all of the NWS severe weather alerts (by US state or by all USA). Then plots them on a map.

**Comment by johnwalicki** [comment]
@jpoeppelman1  If you agree that example is useful, I'll close this ticket?

**Comment by jpoeppelman1** [comment]
Thanks John.  It's a great example, but I was really hoping for a
lightweight alert node to embed into my flow.

**Comment by johnwalicki** [comment]
I was purposeful in constructing the Node-RED-Severe-Weather-Alert-Map flow and Node-RED groups.  It would be relatively easy to grab the half dozen nodes in the center "Query Weather Alert Headline API" group and import them into your flow. That section is portable and has one entry point and one exit.  The top and bottom groups build the Node-RED dashboard/map.  You could ignore those.
![flow](https://raw.githubusercontent.com/johnwalicki/Node-RED-Severe-Weather-Alert-Map/master/screenshots/TWC-SevereWeatherAlerts-flow.png)
