### ISSUE TITLE
Temperatures with point values

### ISSUE THREAD

**Issue by KiCADHugo** [johnwalicki/node-red-contrib-twc-weather#5]
How can i get temperature values like 23.5 °C ? My Bresser weather station shows this values.

**Comment by johnwalicki** [comment]
Hi @KiCADHugo - You can switch between Metric / English / Hybrid units.  Double click on the various node-red-contrib-twc-weather nodes.  Most of them have a "Unit of Measure" property.  Change the drop down to `Metric units`

**Comment by johnwalicki** [comment]
Did that work for you?

**Comment by KiCADHugo** [comment]
on a pws-observations node i use "Metric Units" on Unit of measure, but i receive : 
metric: object
temp: 19
heatIndex: 19
dewpt: 9
windChill: 19
windSpeed: 10
windGust: 11
pressure: 1119.88
precipRate: 0
precipTotal: 0
elev: 12
on wunderground i see the same, only temp 19.

**Comment by johnwalicki** [comment]
Yes - Metric units will return temp in °C
